bugfix/edge-curves
sayari-analytics/trellis pull request #22
Opened 2021-02-26 22:36 UTC by JulietAdams

- Reinitialize edgeIndex on update
- Prevent duplicate pointerEnter events from propagating to user
- Bring subgraph node into foreground on hover

2021-02-26 22:37 UTC, JulietAdams commented
https://github.com/sayari-analytics/trellis/issues/16 and https://github.com/sayari-analytics/trellis/issues/21

2021-02-26 23:30 UTC, jameslaneconkling requested changes
just a simple console.log deletion (we should probably add a lint rule for that...)

I'm a little wary about removing the `if (this.parent === undefined) {`, only b/c I can't quite think through all the implications, and don't remember why I put the check there in the first place. Let's merge, but keep a close eye on graph.develop.sayari.com to see if it introduces any unexpected regressions.

2021-02-26 23:30 UTC, jameslaneconkling commented on src/renderers/webgl/node.ts
> +    console.log('LEAVE', this.node.id, this.node, this.parent?.node.id)
delete

2021-03-03 20:51 UTC, jameslaneconkling approved these changes

2021-03-03 20:51 UTC, merged